### ISSUE TITLE
Not available on Flathub

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.zandronum.Zandronum#1]
Zandronum build seems to be missing. It is not available on Flathub website and cannot be found using GNOME Software or cli flatpak command. I have also noticed that buildbot in the [last commit](https://github.com/flathub/com.zandronum.Zandronum/commit/91631e8c5f5faba652312dfb393530f294bb22d3) has strange url: http://greebo.mooo.com:8010/#builders/12/builds/94

**Comment by bilelmoussaoui** [comment]
I have started a new build here https://flathub.org/builds/#/builders/32/builds/8687 let's see how that goes.

**Comment by AsciiWolf** [comment]
Thanks!

By the way, I have probably found another issue (#2).

**Comment by bilelmoussaoui** [comment]
The build was successful and I have published the game now. I have also assigned the app maintainer to fix the icon size issue.

Thanks for looking into this
