### ISSUE TITLE
Must update for 3.1 version

### ISSUE THREAD

**Issue by N-gV** [flathub/com.zandronum.Zandronum#18]
Flathub port won't updating for 3.1 Zandronum client.

**Comment by Eonfge** [comment]
Hey, thanks for letting me know. I'll look into it later today, but I was warn you that Zandronum has a rather complex pipeline so it might take a bit of time before I get it all working.

https://github.com/flathub/com.zandronum.Zandronum/tree/3.1

**Comment by Eonfge** [comment]
Update is going live.
