### ISSUE TITLE
Document Skins Directory

### ISSUE THREAD

**Issue by Star-Prince** [flathub/com.zandronum.Zandronum#21]
In upstream Zandronum; WADs, PK3s, and other files can be placed in ~/.zandronum/skins to be loaded at start-up. If the directory doesn't exist it can be created.

What is the equivalent directory in this Flatpak?

**Comment by Eonfge** [comment]
Can you give me an `ls -la` of `~/.var/app/com.zandronum.Zandronum/.config/zandronum` and `~/.var/app/com.zandronum.Zandronum/.config/` because I think you're placing them in the wrong folder. You still need to add them into a `skins` folder

**Comment by Star-Prince** [comment]
> Can you give me an `ls -la` of `~/.var/app/com.zandronum.Zandronum/.config/zandronum` and `~/.var/app/com.zandronum.Zandronum/.config/` because I think you're placing them in the wrong folder. You still need to add them into a `skins` folder

`~/.var/app/com.zandronum.Zandronum/.config/zandronum`:
```
total 108
drwxr-xr-x. 1 hknight hknight    54 Feb  8 11:38 .
drwxr-xr-x. 1 hknight hknight    38 Feb  6 19:40 ..
-rw-r--r--. 1 hknight hknight 85170 Feb  7 04:04 auto1.zds
drwxr-xr-x. 1 hknight hknight   234 Feb  6 00:32 skins
-rw-r--r--. 1 hknight hknight 17077 Feb  8 11:38 zandronum.ini
```
`~/.var/app/com.zandronum.Zandronum/.config/`:
```
total 4
drwxr-xr-x. 1 hknight hknight 38 Feb  6 19:40 .
drwxr-xr-x. 1 hknight hknight 56 Feb  8 11:38 ..
drwxr-xr-x. 1 hknight hknight  0 Feb  6 19:52 doomseeker
drwxr-xr-x. 1 hknight hknight 54 Feb  8 11:38 zandronum
```

**Comment by Star-Prince** [comment]
Does the skins directory have to be added as an argument when launching the flatpak?

**Comment by Eonfge** [comment]
Skins should be in the right place.

But should you add it to the argument... I don't know... I have never actually used the Skins in Zandronum. Using Doomseeker it should be very easy to add files to that directory, but I can't tell you how it works.
