### ISSUE TITLE
Not possible to download testing releases

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.zandronum.Zandronum#36]
Many servers now require testing release of Zandronum, however downloading such release does not seem to work:

![1](https://github.com/flathub/com.zandronum.Zandronum/assets/2339930/9f99e6c6-08de-415d-9b01-faea35f153b2)

![2](https://github.com/flathub/com.zandronum.Zandronum/assets/2339930/7da5f928-2bb3-479d-8839-f67cbe2373da)

It looks like that Doomseeker tries to download the archive using a wrong url (wrong version) for some reason:

```
[00:06:23] Downloading Zandronum testing binary from URL: https://zandronum.com/downloads/testing/0.0/ZandroDev0.0-0linux-x86_64.tar.bz2
```

**Comment by AsciiWolf** [comment]
Maybe updating Doomseeker to a more recent build (latest one seems to be 1.4.1) could help?

**Comment by AsciiWolf** [comment]
After manually downloading and copying the alpha build, it looks like that we are missing a dependency:

`/home/asciiwolf/.var/app/com.zandronum.Zandronum/data/doomseeker/plugins/zandronum/3.2-alpha-r221030-0316/zandronum: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

But that's a different problem...

**Comment by Eonfge** [comment]
Got a pull request in the making:

https://github.com/flathub/com.zandronum.Zandronum/pull/37

Won't have to time test it in the coming days, so let me know if it all works as expected

**Comment by AsciiWolf** [comment]
It works! The testing release was successfully downloaded and seems to work fine when using the new build. :-)

Thanks for the quick fix!
