### ISSUE TITLE
Zandronum does not seem to run under Wayland

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.zandronum.Zandronum#4]
The game launched from Doomseeker did not run. This was in log:

```
com.zandronum.Zandronum.desktop[2359]: Could not initialize SDL:
com.zandronum.Zandronum.desktop[2359]: No available video device
```

I am using Fedora 30 Workstation with Wayland and Radeon RX 580. Other Flatpak games work fine.

**Comment by rowbawts** [comment]
Same thing here

**Comment by AsciiWolf** [comment]
I have disabled the `wayland` and `fallback-x11` sockets using _flatpak override_ (also had to re-enable the `x11` one, because it apparently got disabled with fallback-x11). Game now runs and everything works fine with just the x11 socket (and not the Wayland ones) enabled. Even the native GNOME Adwaita theme is now used for Doomseeker.

**Comment by AsciiWolf** [comment]
Oops, sorry, I was wrong. Ignore my previous comment. Everything seems to work fine with the `wayland` socket enabled. The only thing that had to be disabled (removed) was the `fallback-x11` socket. I will send a PR.

**Comment by EchedeyLR** [comment]
> The game launched from Doomseeker did not run. This was in log:
> 
> ```
> com.zandronum.Zandronum.desktop[2359]: Could not initialize SDL:
> com.zandronum.Zandronum.desktop[2359]: No available video device
> ```
> 
> I am using Fedora 30 Workstation with Wayland and Radeon RX 580. Other Flatpak games work fine.

This may be only from flatpak version. I can run official builds without any issue
