### ISSUE TITLE
Zandronum sometimes hangs on exit

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.zandronum.Zandronum#5]
Sometimes, the game hangs on exit and Zandronum process must be manually killed. There is nothing related in the game log. I am on Fedora 30 with Wayland (with the `fallback-x11` socket disabled to workaround #4).

**Comment by Eonfge** [comment]
Mmh, not sure if this is Flatpak related. Have you checked upstream?

I've done some googeling but I could not find anything related.

**Comment by AsciiWolf** [comment]
Nope, I did not check upstream, just the Flatpak version.

**Comment by rowbawts** [comment]
Not sure if related but when I exit the game I get a permanent overlay of graphical artifacts until I reboot. The process is not running at this time.

**Comment by AsciiWolf** [comment]
Huh, that's weird. I just got the [same issue](https://github.com/flathub/org.zdoom.GZDoom/issues/4) on GZDoom today, however Zandronum was working fine the last time I tried it.

**Comment by Eonfge** [comment]
I must admit, Zandronum is a lot less stable then GZDoom. Not sure what there is to do about it, development upstream is going slow.

**Comment by rowbawts** [comment]
> Huh, that's weird. I just got the [same issue](https://github.com/flathub/org.zdoom.GZDoom/issues/4) on GZDoom today, however Zandronum was working fine the last time I tried it. Anyway, I believe the hang is a different issue.

I actually meant GZDoom I'll edit or delete my comment to avoid confusion, posted in this issue by accident.

**Comment by Eonfge** [comment]
Upstream, has been making some changes but nothing ready in any state of release. 

@AsciiWolf Still got the occasional trouble?

**Comment by AsciiWolf** [comment]
@Eonfge I am not sure, I will test it once I get home.

**Comment by AsciiWolf** [comment]
@Eonfge I just tried it on my laptop running Fedora 32 with Wayland and Intel GPU. It seems that the game doesn't hang anymore on exit. However, it now crashes on exit.

**Comment by Eonfge** [comment]
In my book, that's a win :smile: 

But well, thanks for checking. I'll keep this issue open but I don't expect any quick fixes from upstream.

**Comment by AsciiWolf** [comment]
It seems to work fine now and I did not get any crashes/hangs anymore, thanks! :-)
