### ISSUE TITLE
Zandronum does not capture mouse properly

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.zandronum.Zandronum#6]
Zandronum does not seem to capture the mouse pointer properly. I am playing on fullscreen and mouse pointer is frequently causing GNOME Shell activities menu to open (because it touches the top left screen corner) or escaping onto the second monitor. I am on Fedora 30 with Wayland (using [this](https://github.com/flathub/com.zandronum.Zandronum/issues/4#issuecomment-534491940) workaround).

**Comment by AsciiWolf** [comment]
Fixed by re-enabling the `wayland` socket.

**Comment by Star-Prince** [comment]
I'm experiencing an almost identical issue on KDE Plasma 5.23.5 Wayland.

The good news is that switching to the X11 session addresses the issue so it appears to be a viable workaround in the meantime.
